### ISSUE TITLE
Measures fails assigning correct Route

### ISSUE THREAD

**Issue by fuzzysolutions** [blazek/lrs#15]
When trying to assign a route to a point in the _Measures_ tab, the plugin actually takes the very first route that is close enough. It doesn't evaluate wether there is another route closer to the point in question.
This leads to strange behaviour when dealing with several routes close to each other. I'm using LRS in railway context, where distances between parallel tracks are low, same for turnout angles at switches. 
Criterion is the order of route features in the layer, not the ascending route ID, as can be seen in the screenshot below (Route No. 0 is not the fist but the last feature in the layer, thus getting only a single point assigned that was leftover between 1 and 2).
![Image](https://user-images.githubusercontent.com/29453443/32953189-c395d8a0-cbaf-11e7-8d71-b5869392f08b.PNG)
A serious evaluation which route is the nearest would be a more heavy feature, but some relief could already be achieved when there would be the possibility to shrink the _Max point distance_ to a couple of metres.

**Comment by blazek** [comment]
Strange. I checked the code and it should select the nearest line, not the first in threshold. It selects first all route parts in rectangle and then it is loops through all calling closestSegmentWithContext() and the nearest part is selected. I have tried with three lines which are about 1 km distant and threshold 10 km and result is correct.
![lrs-measure](https://user-images.githubusercontent.com/649108/33035798-b4a2f88a-ce2c-11e7-8fe7-fccf14fedf8a.png)
Can you send me the dataset on your snapshot?

The threshold units are the same as generated LRS CRS units and LRS CRS is set to input routes CRS. What CRS have the routes? Geographic - WGS84? Could you try to re-project your input data to projected coordinate system - EPSG 3857 for example and try again with projected data?

LRS in geographic CRS could also be source of wrong distance calculation but I am not sure why. Floating point representation error is the only thing which comes to my mind because values in degrees are small and closestSegmentWithContext() calculates distance square.

**Comment by blazek** [comment]
One another observation from your screenshot: there are both green and blue points near the connection of blue and green line. If it was really the first line in the threshold which takes the point, there would be only green or blue points where the lines are close enough to each other. 

A line assigned to a point does not seem to be random, because green and blue point areas do not overlap. It's not sure however because there is not enough points. 

Your measured points and route lines are in the same CRS including datum shift?

**Comment by fuzzysolutions** [comment]
Here's my snapshot. Its just an example of random points and lines I created in order to demonstrate the behavior. CRS is WGS84 for all layers, i run the plugin with OTF reprojection to EPSG:3857.
I'll test further and take a look into the plugin code.

[LRS Snapshot.zip](https://github.com/blazek/lrs/files/1490665/LRS.Snapshot.zip)

**Comment by blazek** [comment]
The code finding a route is here https://github.com/blazek/lrs/blob/0dff2ee/lrs/lrs.py#L648

**Comment by fuzzysolutions** [comment]
Thanks!
Just a remark on my snapshot:
The plugin doesn't recognise the _Measure_ field in the _ReferencePoint_ layer as a number since i saved the layer and restarted QGIS, thus it doesn't display it in the _Measure field_ dropdown. When you add an own field _Measure2_ with the same values, it works (until you save the layer and restart QGIS ...).

**Comment by fuzzysolutions** [comment]
After some closer look, I can specify the problem:
Line 662, `geo.closestSegmentWithContext(point)` returns `0.0` for `sqDist` when dealing with very close `point` and `geo`. Hence, the check `if dist <= nearestDist` is true for the first id being tested. `nearestDist` is then being updated to the new closest distance. When another id is being tested, new `dist` is `0.0` as well, but that is not lower than `0.0`.
Normal behavior occurs only when the first id is far enough to give a `dist` higher than `0.0`. Here, another id that is closer (even `0.0`) can override the first id).

So I have to dig into the `closestSegmentWithContext()` code or try with other CRS settings.

**Comment by blazek** [comment]
Good catch! It seems that QgsGeometryUtils::sqrDistToLine() returns zero if dist is smaller than epsilon which defaults to DEFAULT_SEGMENT_EPSILON = 1e-8 
https://github.com/qgis/QGIS/blob/final-2_18_13/src/core/geometry/qgsgeometryutils.cpp#L278

Where one degree has about 70km, 1m square = 2*10e-10 and zero is returned.

**Comment by blazek** [comment]
Unfortunately, epsilon cannot be used as parameter for closestSegmentWithContext() in Python. There is no simple fix. Please use projected layers and I'll fix this in plugin 1.x upgraded to QGIS 3.

I found another issue #16.

**Comment by fuzzysolutions** [comment]
Thanks for your support. When saving all layers in UTM, route assignment works fine.

![16 qgis_lrs_measures_correct_behavior](https://user-images.githubusercontent.com/29453443/33170176-a7faa28c-d047-11e7-9228-570bc1920a0d.PNG)

**Comment by blazek** [comment]
Fixed in 8424eb6 for QGIS3 but requires QGIS 3 Python API change for which I am going to create pull request.

**Comment by blazek** [comment]
https://github.com/qgis/QGIS/pull/5755
