### ISSUE TITLE
Generated features display incorrectly

### ISSUE THREAD

**Issue by simonsouth** [blazek/lrs#30]
In some cases the features generated for events (via the plugin's "Events" tab) will display incorrectly, appearing to float off in a distant corner of the map rather than superimposed over their source features.

The issue is that the layer created to hold the generated features is assigned (in `LrsEvents.create()`) the CRS configured as the default for the project, but the features it contains naturally use coordinates derived from the layer with measures. When the layer with measures uses a CRS different from the project's default, the generated features will appear in the wrong location on the map (until the new layer is reconfigured to use the correct CRS).

The best solution is probably to have the new layer inherit the CRS of the source (measure) layer rather than that of the project, since I think this is what would normally be expected. If the user wants the newly created layer to use a different CRS instead, it can easily be reprojected as a separate step.

**Comment by blazek** [comment]
I am not completely sure that "The best solution is probably to have the new layer inherit the CRS of the source (measure) layer rather than that of the project, since I think this is what would normally be expected." Project CRS may be expected as well, I think. At least coordinates precision is not lost doing unintended re-projection in this case. Merging.
