### ISSUE TITLE
Please add capability to work with existing routes

### ISSUE THREAD

**Issue by mgincnj** [blazek/lrs#4]
Currently your plugin requires the user to calibrate a route system before it can be used.  This means it can't be used to segment an existing route table.  There is a plugin that is supposed to support such segmentation, but in my experience it doesn't work very well (well, I can't get it to work).  It would be great if this capability could be added to your plugin.

**Comment by gis-haderslev** [comment]
Hello we are interested in such one extension - to segment an existing route table. Can you give us an estimate price for your work?

**Comment by blazek** [comment]
I'll post specification and cost estimate here. First, let us discuss how it should work to possibly cover all needs. 

To be clear, existing route table means a layer with M (measures), right? If not, what does it mean for you exactly?

The plugin was written when QGIS hadn't support for M, that's one of reasons why it is not using layer with M primarily. My idea for future enhancements is to have two sets of tools:

1. Tools for use of an existing LRS (existing layer with M)
    1. Locate an event (zoom)
    2. Create events (create new layer)
    3. Calculate measures create/update table
2. Tools for creation/calibration of a new LRS (new layer with M)
    1. Calibrate from lines + milestones (current Calibration tab)
    2. Generate from lines with start / (end) attributes
    3. Generate from simple lines assuming that start is 0 and geometry length corresponds to real length 

This also means using the same order of tabs as the tools above. Direct export to PostGIS may be thrown away, because QGIS should be able to export a layer with M to formats which support it, at least PostGIS and Shapefile (but I am not sure if it really is).

The plugin also needs upgrade to QGIS 3, which I started already but not yet finished facing the quantity of changes required. Merging new enhancements to QGIS 3 version could be complicated, so the question, is it acceptable for users to do the port to QGIS 3 first and then the enhancements in QGIS 3 version. AFAIK, QGIS 3 stable could be released in July 2017.

**Comment by andreasneumann** [comment]
One question: could the LR functionality be made a part of QGIS core instead of having it as a plugin?

Maybe there are good reasons to have it is a plugin, but maybe it could also be made a core QGIS functionality.

**Comment by haubourg** [comment]
> ...PostGIS and Shapefile (but I am not sure if it really is).

yes it works with ShapeM, and also sqlite / GPKG 

> Tools for creation/calibration of a new LRS (new layer with M)
Generate from lines with start / (end) attributes

in many cases, you have datasets made of several linestrings with a common route attribute and each segment has from_measure and to_measure. Calibrating a route is usually doing a linemerge on this common ID . That linemerge can be tricky since it is necessary to check real connectivity and coherent linestring direction between segments. BTW. I miss that function in Postgis also. 

..and to go with last minute's comment from @andreasneumann, yes that fits well a a core feature now that z/m values are natively supported

**Comment by blazek** [comment]
>  could the LR functionality be made a part of QGIS core instead of having it as a plugin

I also considered that, but except the 1.i "Locate event", it is creating new data as a result of non generic data processing, all such functionalities usually go to plugins AFAICT, especially for ease of QGIS core maintenance, I believe. I can imagine that as a core plugin, but it still brings new troubles to core developers.

**Comment by blazek** [comment]
> That linemerge can be tricky since it is necessary to check real connectivity and coherent linestring direction between segments

You get into the same problems (and to much more) with current lines+milestones. Only a human can resolve them.  That is why there is the support for error detection and localization. The greatest value of the plugin is currently in LRS data maintenance, which is impossible without good error detection. Other standard segmentation tools are easy. I cannot say to which extent it will be possible, but I would like to use existing calibration procedures also for lines+start/end.

**Comment by gis-haderslev** [comment]
> To be clear, existing route table means a layer with M (measures), right? If not, what does it mean for you exactly?

It is right. As @haubourg wrote existing route table means a layer with M and ID field 
We have to create events layer (Points or Lines) using a event table (can be without geometry) that contains ID and one measure field (for Points events) or two measure fields (**from_measure** and **to_measure** for Lines events).
So we need actually Tools 1
```
1. Tools for use of an existing LRS (existing layer with M)

i. Locate an event (zoom)
ii. Create events (create new layer)
iii. Calculate measures create/update table
```
especially **Create events (create new layer)**

**Comment by gis-haderslev** [comment]
> Merging new enhancements to QGIS 3 version could be complicated, so the question, is it acceptable for users to do the port to QGIS 3 first and then the enhancements in QGIS 3 version. AFAIK, QGIS 3 stable could be released in July 2017.

Totally agree. It could be nice to have it in the new LTR version. We can wait.

**Comment by blazek** [comment]
OK, it seems all to be clear. I'll post specification in coming days (now I'm ill). I hope that the work will be cofinanced by more subjects and it will be done all in one stroke. 

With respect to the possible move to QGIS core, I'm not strongly against, what I wrote was just my opinion open for further discussion. The other contra the move is bugfixing, which may take long time for core plugins (to get to user) and does not cover older QGIS versions. My last idea is to do the proposed refactoring within the standalone plugin with possible future split and move of the first set of tools (1. Tools for use of an existing LRS) to the core Python plugin, once the functionality is stabilized (if it will be still considered to be useful).

**Comment by blazek** [comment]
I have created detailed document about upgrade https://github.com/blazek/lrs/blob/master/upgrade.md

Now we are trying to find funds, if you are interested in the upgrade and you would like to contribute, please contact me: radim.blazek@gmail.com

**Comment by blazek** [comment]
I have uploaded the upgraded plugin to repository.
