### ISSUE TITLE
Coredump after calibration

### ISSUE THREAD

**Issue by merkato** [blazek/lrs#9]
On Xubuntu 16.04, QGIS 2.16 after Calibration, when progress bar reaches 93% QGIS crashes with segfault. 

dmesg output:

[ 1170.809232] qgis.bin[3915]: segfault at 31 ip 00007f3573c4dbab sp 00007fffd40a6f00 error 4 in libqgis_core.so.2.16.0[7f3573404000+9dd000]
[ 1377.082829] qgis.bin[5060]: segfault at 8 ip 00007ff6027e5265 sp 00007ffc4f30ef90 error 4 in libQtCore.so.4.8.7[7ff602719000+2e7000]

On Windows 10, QGIS 2.15, 2.16 with same dataset every thing is OK.

**Comment by blazek** [comment]
I would need backtrace, can you try to produce backtrace? Instractions are here (which I believe apply also to Xubuntu) https://wiki.debian.org/HowToGetABacktrace.

One guess is that it could be some null/degenerated geometry or attribute, could you try to bisect the feature causing the crash? It means take always half of routes and half of the crashing half etc. until you find the feature causing crash. If the dataset is not large, you can manually include/exclude routes in the plugin GUI, otherwise use qgis tools to divide the data.

Is it the dataset public, can you put it somewhere on the web?

**Comment by merkato** [comment]
Hi, 

This bug is reproducible on any dataset on this machine. I've tried to reinstall QGIS from repositories, even by purge. This doesn't change anything.

I've used OpenStreetMap data from Poland, imported to psql by imposm3.
I'll try to produce backtrace.

**Comment by merkato** [comment]
gdb hangs, QGIS hangs, everything else works. Nice. Trying again.


[lrs_crash_reproduce.zip](https://github.com/blazek/lrs/files/400045/lrs_crash_reproduce.zip)
![lrs_settings_before_crash](https://cloud.githubusercontent.com/assets/847295/17375493/7c5d7446-59b1-11e6-9e6e-e630d2954944.png)
[gdb-qgis.txt](https://github.com/blazek/lrs/files/400062/gdb-qgis.txt)

[Backtrace in Ubuntu](https://wiki.ubuntu.com/Backtrace)

**Comment by blazek** [comment]
It seems to be crashing in QWebFrame::setHtml(), can you try to delete/comment line 1235 in your $HOME/.qgis2/python/plugins/lrs/lrsdockwidget.py? This line:
`
self.statsWebView.setHtml( html )
`
It is just setting stats info window.

**Comment by merkato** [comment]
Yes. That's it!!! Thanks. 

It seems that this is general problem in QGIS 2.16 - QuickOSM suffers same problem, doesn't even start. At this point it suspected that WITH_QTWEBKIT=FALSE is problem.

#https://github.com/3liz/QuickOSM/issues/84
http://hub.qgis.org/issues/14881

**Comment by blazek** [comment]
The fix will be in release 0.3.7.

**Comment by blazek** [comment]
0.3.7 is release and uploaded to plugins repository.
